### ISSUE TITLE
Github action for reserving multiple machines with multi-device agent

### ISSUE THREAD

**Issue by marosg42** [canonical/testflinger#415]
GH action to reserve one machine works great.
However there is also multi device agent which allows to reserve several machines at once and they behave as a group, either all are reserved or job fails.
Input for the action will be valid Testflinger job in yaml file.
Output will be two lists
- list of job ids of reservation jobs (so that they can be cancelled when machines are not needed before timeout)
- list of IPs of reserved machines

To avoid complexity action can require that job always contains reservation data and never test or other than provisioning data

**Comment by mz2** [comment]
@marosg42 could you describe the output you'd expect from testflinger-cli exactly, please?

**Comment by marosg42** [comment]
Similar to single job action which has
```
outputs:
  id:
    description: 'The ID of the submitted job'
    value: ${{ steps.submit.outputs.id }}
  device-ip:
    description: 'The IP of the reserved device (if applicable)'
    value: ${{ steps.track-reservation.outputs.ip }}
```
This will output JSON list of job ids and a JSON list of device-ips.
