### ISSUE TITLE
Submitting a job with only filter without job_queue

### ISSUE THREAD

**Issue by nobuto-m** [canonical/testflinger#454]
This is an enhancement request, and I'm quite new to the testflinger so I'm not sure if this request makes sense to the team or not.

Let's say I have a job that needs a x86 physical machine but the job is server model agnostic. It seems that I should do a search first with specs like the following.

```
in_testflinger:true tf_provision_type:maas2 category:Server arch:amd64 memory_gte:128000000000 memory_lte:256000000000
```

Then, select a machine/agent/queue by myself to use the following.

```yaml
job_queue: "<JOB_QUEUE>"
provision_data:
  distro: noble
test_data:
...
```

Is it a crazy idea if we can pass the filter as is to the testflinger command, then the selection of a machine happens automatically? I'm assuming something like:

```yaml
agent_filter: 'in_testflinger:true tf_provision_type:maas2 category:Server arch:amd64 memory_gte:128000000000 memory_lte:256000000000'
provision_data:
  distro: noble
test_data:
...
```
